[package]
name = "taxcy"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
num-traits = "0.2.19"
cli-table = "0.5.0"
rusty-money = { version = "0.4.1", features = ["iso"] }
